# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time


name: Java CI with Maven

on:
  push:
    branches: [ "main3" ]
  pull_request:
    branches: [ "main3" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests with Maven
      run: mvn test --file pom.xml
      continue-on-error: true

    - name: Generate Test Report
      if: failure()
      run: |
        echo "Test failures detected. Generating report..."
        mkdir -p test-reports
        cp target/surefire-reports/*.xml test-reports/
        echo "Copy result:"
        ls test-reports

    - name: Send success message to Telegram
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Всё ок"
        
    - name: Make failed test report
      if: failure()
      run: |
          set +e
          cat test-reports/*.xml > failed-test-report.xml
    
    - name: Send failure message to Telegram
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Некоторые тесты не пройдены:"
        document: failed-test-report.xml
